import {
  Game,
  Review,
  User,
  GameList,
  ActivityItem,
} from "./types";
import { coverUrl, screenshotUrl, avatarUrl } from "./utils";

/* ═══════════════════════════════════════════════════
   GAMES — 22 deterministic entries mixing PC + Android
   ═══════════════════════════════════════════════════ */

export const games: Game[] = [
  {
    id: "g1",
    slug: "hades-ii",
    title: "Hades II",
    subtitle: "Supergiant's mythic sequel",
    coverImage: coverUrl("hades-ii"),
    headerImage: coverUrl("hades-ii-header", 1200, 500),
    screenshots: [1, 2, 3, 4].map((i) => screenshotUrl("hades-ii", i)),
    platforms: ["PC"],
    genres: ["Roguelike", "Action"],
    tags: ["Greek Mythology", "Roguelite", "Fast-Paced", "Indie"],
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    releaseDate: "2025-09-18",
    description:
      "Hades II sends you from the Underworld to the surface in an all-new roguelike that doubles down on every system that made the original legendary. Play as Melinoë, sister of Zagreus, as you battle through chaotic realms of Greek myth to confront Chronos, the Titan of Time.",
    score: 94,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "A near-flawless sequel that refines the roguelike formula with deeper builds, richer narrative, and jaw-dropping art direction.",
    pros: [
      "Deep build variety keeps every run feeling fresh",
      "Gorgeous hand-painted art and fluid animation",
      "Narrative hooks that make you say 'one more run' at 2 AM",
      "Outstanding soundtrack by Darren Korb",
    ],
    cons: [
      "Early-access roots show in a few unfinished edges",
      "Can feel overwhelming with the number of systems to track",
    ],
    monetization: "Paid",
    performanceNotes:
      "Runs at 120 fps on mid-range hardware. Excellent Steam Deck support with verified status. VRAM usage stays under 3 GB even at max settings.",
    monetizationNotes:
      "One-time purchase with no microtransactions. All post-launch content delivered free.",
    steamUrl: "https://store.steampowered.com/app/1145350/Hades_II/",
    reviewCount: 4820,
    userScore: 92,
    featured: true,
    trending: true,
  },
  {
    id: "g2",
    slug: "elden-ring",
    title: "Elden Ring",
    subtitle: "The Lands Between await",
    coverImage: coverUrl("elden-ring"),
    headerImage: coverUrl("elden-ring-header", 1200, 500),
    screenshots: [1, 2, 3, 4].map((i) => screenshotUrl("elden-ring", i)),
    platforms: ["PC"],
    genres: ["Action RPG", "Open World"],
    tags: ["Soulslike", "Dark Fantasy", "Exploration", "Co-op"],
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseDate: "2022-02-25",
    description:
      "Rise, Tarnished. Elden Ring is a sprawling open-world action RPG set in The Lands Between—a realm of shattered grace crafted by Hidetaka Miyazaki and George R. R. Martin. If you enjoy demanding combat and generous exploration, this is the pinnacle.",
    score: 96,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "An epoch-defining RPG that merges Souls-caliber combat with the scope of an open world. Unrivaled in ambition and execution.",
    pros: [
      "Staggering open-world design with secrets around every corner",
      "Deep, flexible combat with dozens of viable build paths",
      "Cooperative and PvP multiplayer adds meaningful variety",
      "DLC Shadow of the Erdtree is one of the best expansions ever made",
    ],
    cons: [
      "PC port had rough launch performance (largely patched now)",
      "Difficulty can wall off less experienced players",
    ],
    monetization: "Paid",
    performanceNotes:
      "Post-patch, stable 60 fps on recommended specs. Dense areas may still see dips on older GPUs. Controller strongly recommended.",
    monetizationNotes: "Base game + paid DLC. No microtransactions.",
    steamUrl: "https://store.steampowered.com/app/1245620/ELDEN_RING/",
    reviewCount: 12400,
    userScore: 94,
    trending: true,
  },
  {
    id: "g3",
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    subtitle: "The RPG of a generation",
    coverImage: coverUrl("baldurs-gate-3"),
    headerImage: coverUrl("bg3-header", 1200, 500),
    screenshots: [1, 2, 3, 4].map((i) => screenshotUrl("bg3", i)),
    platforms: ["PC"],
    genres: ["RPG", "Turn-Based Strategy"],
    tags: ["D&D", "Story Rich", "Choices Matter", "CRPG"],
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseDate: "2023-08-03",
    description:
      "An epic RPG set in the Dungeons & Dragons universe. Forge your path through a tale of fellowship and betrayal, survival and sacrifice. Alone or with friends, decide the fate of the Forgotten Realms in a narrative that truly responds to your choices.",
    score: 97,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "The most reactive RPG ever made. Every playthrough uncovers new paths, characters, and consequences. A genre-defining masterpiece.",
    pros: [
      "Unparalleled reactivity to player choices",
      "Stellar voice acting and cinematic presentation",
      "4-player co-op with full freedom for each player",
      "Hundreds of hours of unique content",
    ],
    cons: [
      "Act 3 can feel less polished than earlier acts",
      "Turn-based combat may not appeal to action RPG fans",
    ],
    monetization: "Paid",
    performanceNotes:
      "Demands a decent GPU for max settings. Vulkan renderer recommended on AMD. Load times are fast on SSD.",
    monetizationNotes: "One-time purchase. No DLC or microtransactions announced.",
    steamUrl: "https://store.steampowered.com/app/1086940/Baldurs_Gate_3/",
    reviewCount: 18200,
    userScore: 96,
    featured: true,
  },
  {
    id: "g4",
    slug: "stardew-valley",
    title: "Stardew Valley",
    subtitle: "Farm, fish, and find love",
    coverImage: coverUrl("stardew-valley"),
    headerImage: coverUrl("stardew-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("stardew", i)),
    platforms: ["PC", "Android"],
    genres: ["Simulation", "RPG"],
    tags: ["Farming", "Pixel Art", "Relaxing", "Indie"],
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    releaseDate: "2016-02-26",
    description:
      "Escape to the countryside and build the farm of your dreams. Stardew Valley is a charming farming sim that transcends the genre with deep systems, heartfelt storytelling, and an absurd amount of content for a solo developer's labor of love.",
    score: 95,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "The gold standard of farming sims. Warm, generous, and endlessly replayable—both on desktop and mobile.",
    pros: [
      "Years of free content updates from a passionate solo developer",
      "Deeply satisfying gameplay loop across farming, mining, and relationships",
      "Android port is thoughtfully adapted with touch controls",
      "Great for short sessions or marathon plays",
    ],
    cons: [
      "Graphics are simple pixel art (a style, not a flaw—but not for everyone)",
      "Early game can feel slow before systems open up",
    ],
    monetization: "Paid",
    performanceNotes:
      "Runs on almost anything. Smooth 60 fps on budget phones and low-end PCs alike.",
    monetizationNotes: "Pay once, get everything. Zero monetization beyond purchase price.",
    steamUrl: "https://store.steampowered.com/app/413150/Stardew_Valley/",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.chucklefish.stardewvalley",
    reviewCount: 22600,
    userScore: 96,
    trending: true,
  },
  {
    id: "g5",
    slug: "celeste",
    title: "Celeste",
    subtitle: "Climb. Fall. Try again.",
    coverImage: coverUrl("celeste"),
    headerImage: coverUrl("celeste-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("celeste", i)),
    platforms: ["PC"],
    genres: ["Platformer", "Indie"],
    tags: ["Precision", "Pixel Art", "Story Rich", "Difficult"],
    developer: "Maddy Makes Games",
    publisher: "Maddy Makes Games",
    releaseDate: "2018-01-25",
    description:
      "Help Madeline survive her journey to the top of Celeste Mountain. Brave hundreds of hand-crafted challenges in this super-tight platformer with an emotional narrative about anxiety, perseverance, and self-discovery.",
    score: 92,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "Precision platforming at its absolute best, wrapped in a story that will genuinely move you. A masterclass in game design.",
    pros: [
      "Pixel-perfect controls that feel incredible",
      "Beautiful narrative about mental health woven into gameplay",
      "Assist mode makes it accessible without diminishing the experience",
      "Exceptional original soundtrack",
    ],
    cons: [
      "Later chapters demand serious skill investment",
      "Short base runtime if you skip B/C-sides",
    ],
    monetization: "Paid",
    performanceNotes:
      "Extremely lightweight. Runs flawlessly on integrated graphics.",
    monetizationNotes: "One-time purchase. All DLC content delivered free.",
    steamUrl: "https://store.steampowered.com/app/504230/Celeste/",
    reviewCount: 8900,
    userScore: 93,
  },
  {
    id: "g6",
    slug: "dead-cells",
    title: "Dead Cells",
    subtitle: "Die. Learn. Repeat.",
    coverImage: coverUrl("dead-cells"),
    headerImage: coverUrl("dead-cells-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("dead-cells", i)),
    platforms: ["PC", "Android"],
    genres: ["Roguelike", "Action"],
    tags: ["Metroidvania", "Pixel Art", "Difficult", "Indie"],
    developer: "Motion Twin",
    publisher: "Motion Twin",
    releaseDate: "2018-08-07",
    description:
      "Dead Cells marries the roguelike with tight Metroidvania action. Every run teaches you something new as you slash through procedurally generated levels filled with dangerous enemies and rewarding secrets.",
    score: 89,
    verdictLabel: "WORTH IT",
    verdictSummary:
      "Snappy combat and permanent progression make this one of the most replayable roguelikes on any platform.",
    pros: [
      "Razor-sharp combat feels phenomenal",
      "Excellent Android port with good touch controls",
      "Frequent DLC expansions keep the game alive",
      "Incredible variety in weapon/skill combinations",
    ],
    cons: [
      "RNG can create frustrating weapon pools",
      "Mobile version occasionally stutters on older devices",
    ],
    monetization: "Paid",
    performanceNotes:
      "PC runs at 144+ fps trivially. Android version targets 60 fps on mid-range and above.",
    monetizationNotes: "Base game paid. Several paid DLC packs add new biomes and bosses.",
    steamUrl: "https://store.steampowered.com/app/588650/Dead_Cells/",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.playdigious.deadcells.mobile",
    reviewCount: 6700,
    userScore: 87,
  },
  {
    id: "g7",
    slug: "genshin-impact",
    title: "Genshin Impact",
    subtitle: "Open world of Teyvat",
    coverImage: coverUrl("genshin"),
    headerImage: coverUrl("genshin-header", 1200, 500),
    screenshots: [1, 2, 3, 4].map((i) => screenshotUrl("genshin", i)),
    platforms: ["PC", "Android"],
    genres: ["Action RPG", "Open World"],
    tags: ["Gacha", "Anime", "Exploration", "Co-op"],
    developer: "miHoYo",
    publisher: "miHoYo",
    releaseDate: "2020-09-28",
    description:
      "Explore the vast world of Teyvat across seven distinct nations, each with their own elemental archon. Genshin Impact delivers stunning visuals, deep elemental combat, and a sprawling story that continues to grow with every major update.",
    score: 78,
    verdictLabel: "WORTH IT",
    verdictSummary:
      "A breathtaking open world with satisfying combat, undercut by aggressive gacha monetization. Incredible if you stay free-to-play disciplined.",
    pros: [
      "Stunning anime-style open world that's constantly expanding",
      "Deep elemental reaction combat system",
      "Generous free-to-play experience for the main story",
      "Cross-platform play between PC and mobile",
    ],
    cons: [
      "Gacha system preys on spending psychology",
      "Resin (stamina) system gates daily progression",
      "Late-game content drought between patches",
    ],
    monetization: "Free with IAP",
    performanceNotes:
      "Gorgeous on PC at max settings (60 fps). Android version scales well but drains battery aggressively. 8 GB+ RAM phone recommended.",
    monetizationNotes:
      "Free to play. Revenue comes from character/weapon gacha banners. Prices start at $1 and go up to $100 per top-up. Can be fully enjoyed without spending, but requires patience.",
    steamUrl: "https://store.steampowered.com/app/2462650/Genshin_Impact/",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact",
    reviewCount: 15600,
    userScore: 75,
    trending: true,
  },
  {
    id: "g8",
    slug: "minecraft",
    title: "Minecraft",
    subtitle: "Build anything. Explore everything.",
    coverImage: coverUrl("minecraft"),
    headerImage: coverUrl("minecraft-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("minecraft", i)),
    platforms: ["PC", "Android"],
    genres: ["Sandbox", "Survival"],
    tags: ["Creative", "Multiplayer", "Modding", "Voxel"],
    developer: "Mojang Studios",
    publisher: "Microsoft",
    releaseDate: "2011-11-18",
    description:
      "The best-selling game of all time. Minecraft is a sandbox adventure where you place blocks, craft tools, and explore an infinite procedurally generated world—alone or with friends.",
    score: 93,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "Timeless. Minecraft is as relevant today as it was in 2011, with an ecosystem of mods and community content that keeps it endlessly fresh.",
    pros: [
      "Infinite creative potential with mods and resource packs",
      "Cross-play across nearly every platform",
      "Regular free updates that add meaningful content",
      "One of the best multiplayer experiences ever",
    ],
    cons: [
      "Java Edition and Bedrock Edition split is confusing",
      "Vanilla survival can feel repetitive without mods",
    ],
    monetization: "Paid",
    performanceNotes:
      "Java Edition benefits from mods like Sodium. Bedrock (Android) is well-optimized for mobile hardware.",
    monetizationNotes:
      "Paid once. Bedrock has a Marketplace for cosmetics/maps but all gameplay is in the base purchase.",
    steamUrl: "https://www.minecraft.net/",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.mojang.minecraftpe",
    reviewCount: 31200,
    userScore: 91,
  },
  {
    id: "g9",
    slug: "hollow-knight",
    title: "Hollow Knight",
    subtitle: "Into the depths of Hallownest",
    coverImage: coverUrl("hollow-knight"),
    headerImage: coverUrl("hollow-knight-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("hollow-knight", i)),
    platforms: ["PC"],
    genres: ["Metroidvania", "Action"],
    tags: ["Atmospheric", "Difficult", "Indie", "Exploration"],
    developer: "Team Cherry",
    publisher: "Team Cherry",
    releaseDate: "2017-02-24",
    description:
      "Descend into Hallownest, a vast underground kingdom of insects and heroes. Hollow Knight is a beautifully hand-drawn 2D Metroidvania with challenging combat, a hauntingly atmospheric world, and an absurd amount of content for the price.",
    score: 94,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "One of the greatest Metroidvanias ever crafted. Its world, combat, and atmosphere are in a league of their own.",
    pros: [
      "Massive, interconnected world with incredible hand-drawn art",
      "Tight, responsive combat with satisfying boss fights",
      "40+ hours of content for a budget price",
      "Atmospheric soundtrack by Christopher Larkin",
    ],
    cons: [
      "Map system can be frustrating for navigation",
      "Some areas require extensive backtracking",
    ],
    monetization: "Paid",
    performanceNotes:
      "Runs perfectly on virtually any hardware. Great on Steam Deck.",
    monetizationNotes:
      "One-time purchase. All four content packs were released completely free.",
    steamUrl: "https://store.steampowered.com/app/367520/Hollow_Knight/",
    reviewCount: 14300,
    userScore: 95,
  },
  {
    id: "g10",
    slug: "terraria",
    title: "Terraria",
    subtitle: "Dig, fight, explore, build",
    coverImage: coverUrl("terraria"),
    headerImage: coverUrl("terraria-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("terraria", i)),
    platforms: ["PC", "Android"],
    genres: ["Sandbox", "Action"],
    tags: ["Survival", "Crafting", "2D", "Multiplayer"],
    developer: "Re-Logic",
    publisher: "Re-Logic",
    releaseDate: "2011-05-16",
    description:
      "The 2D sandbox adventure with boss fights, base building, and an endgame that rivals many full-price RPGs. Terraria has been updated for over a decade and has one of the most passionate communities in gaming.",
    score: 91,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "Still getting free updates after 13 years. Terraria is a bottomless well of discovery, combat, and creativity.",
    pros: [
      "Staggering amount of content for the price",
      "Combat progression is deeply satisfying",
      "Multiplayer is endlessly fun",
      "Android port is surprisingly complete",
    ],
    cons: [
      "Mobile controls can be fiddly for boss fights",
      "The early game doesn't convey the depth ahead",
    ],
    monetization: "Paid",
    performanceNotes:
      "Ultra lightweight on PC. Android version handles large worlds well on modern devices.",
    monetizationNotes: "One-time purchase. Over a decade of free content updates.",
    steamUrl: "https://store.steampowered.com/app/105600/Terraria/",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.and.games505.TerrariaPaid",
    reviewCount: 19800,
    userScore: 93,
  },
  {
    id: "g11",
    slug: "slay-the-spire",
    title: "Slay the Spire",
    subtitle: "Cards. Combat. Ascend.",
    coverImage: coverUrl("slay-spire"),
    headerImage: coverUrl("slay-spire-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("slay-spire", i)),
    platforms: ["PC", "Android"],
    genres: ["Roguelike", "Card Game"],
    tags: ["Strategy", "Deckbuilding", "Indie", "Turn-Based"],
    developer: "MegaCrit",
    publisher: "Humble Games",
    releaseDate: "2019-01-23",
    description:
      "The game that invented the roguelike deckbuilder genre. Slay the Spire fuses card strategy with permadeath runs in a system so perfectly balanced that every loss teaches and every win thrills.",
    score: 90,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "The genre-defining roguelike deckbuilder. Perfectly balanced, endlessly compelling, and brilliant on mobile.",
    pros: [
      "Near-perfect strategic balance across all characters",
      "Quick enough for a single bus-ride run",
      "Android port is excellent with intuitive touch controls",
      "Immense replay value with daily challenges and mod support",
    ],
    cons: [
      "Visuals are functional rather than beautiful",
      "Can feel like pure luck on high Ascension levels",
    ],
    monetization: "Paid",
    performanceNotes:
      "Minimal system requirements on any platform. Battery-efficient on Android.",
    monetizationNotes: "Pay once. No IAP, no ads, no premium currency.",
    steamUrl: "https://store.steampowered.com/app/646570/Slay_the_Spire/",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.humble.SlayTheSpire",
    reviewCount: 10100,
    userScore: 91,
  },
  {
    id: "g12",
    slug: "monument-valley",
    title: "Monument Valley",
    subtitle: "Impossible architecture. Perfect puzzles.",
    coverImage: coverUrl("monument"),
    headerImage: coverUrl("monument-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("monument", i)),
    platforms: ["Android"],
    genres: ["Puzzle", "Adventure"],
    tags: ["Artistic", "Relaxing", "Short", "Beautiful"],
    developer: "ustwo games",
    publisher: "ustwo games",
    releaseDate: "2014-04-03",
    description:
      "Guide silent princess Ida through mysterious monuments of optical illusion and impossible geometry in this award-winning puzzle game. Monument Valley is a journey through fantastical architecture, impossible geometry, and mysterious monuments.",
    score: 88,
    verdictLabel: "WORTH IT",
    verdictSummary:
      "A brief but unforgettable visual poem. One of the most beautiful mobile games ever made.",
    pros: [
      "Absolutely gorgeous Escher-inspired visual design",
      "Intuitive touch-based puzzle mechanics",
      "Perfect for a relaxing play session",
      "Runs beautifully on any device",
    ],
    cons: [
      "Very short — completable in under 2 hours",
      "Puzzles are more atmospheric than challenging",
    ],
    monetization: "Paid",
    performanceNotes: "Featherlight performance requirements.",
    monetizationNotes: "One-time purchase. Expansion pack available as separate buy.",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.ustwo.monumentvalley",
    reviewCount: 5400,
    userScore: 89,
  },
  {
    id: "g13",
    slug: "altos-odyssey",
    title: "Alto's Odyssey",
    subtitle: "Sandboard into the sunset",
    coverImage: coverUrl("altos-odyssey"),
    headerImage: coverUrl("altos-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("altos", i)),
    platforms: ["Android"],
    genres: ["Endless Runner", "Adventure"],
    tags: ["Relaxing", "Beautiful", "Casual", "Atmospheric"],
    developer: "Snowman",
    publisher: "Snowman",
    releaseDate: "2018-07-25",
    description:
      "Journey across the beautiful and mysterious desert of Alto's Odyssey. Discover the secrets of the sand dunes, canyons, and ancient temples as you sandboard through procedurally generated terrain.",
    score: 82,
    verdictLabel: "WORTH IT",
    verdictSummary:
      "A serene, gorgeous endless runner that's perfect for unwinding. Great in small doses.",
    pros: [
      "Breathtaking dynamic weather and lighting system",
      "Zen mode removes all objectives for pure relaxation",
      "Silky smooth controls",
      "Top-tier ambient soundtrack",
    ],
    cons: [
      "Limited depth beyond score chasing",
      "In-app purchases for cosmetics feel unnecessary",
    ],
    monetization: "Free with IAP",
    performanceNotes: "Runs beautifully on budget devices.",
    monetizationNotes:
      "Free to play with optional cosmetic purchases. No pay-to-win mechanics.",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.noodlecake.altosodyssey",
    reviewCount: 3200,
    userScore: 80,
  },
  {
    id: "g14",
    slug: "the-witcher-3",
    title: "The Witcher 3: Wild Hunt",
    subtitle: "A story you won't forget",
    coverImage: coverUrl("witcher3"),
    headerImage: coverUrl("witcher3-header", 1200, 500),
    screenshots: [1, 2, 3, 4].map((i) => screenshotUrl("witcher3", i)),
    platforms: ["PC"],
    genres: ["Action RPG", "Open World"],
    tags: ["Story Rich", "Dark Fantasy", "Choices Matter", "Mature"],
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    releaseDate: "2015-05-19",
    description:
      "As the professional monster hunter Geralt of Rivia, traverse a vast open world rich with merchant cities, pirate islands, dangerous mountain passes, and forgotten caverns. The Witcher 3: Wild Hunt is a story of choices and consequences.",
    score: 96,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "A landmark in RPG storytelling. Ten years later, The Witcher 3's world, quests, and characters remain the benchmark.",
    pros: [
      "Some of the best sidequests ever written in an RPG",
      "Hearts of Stone and Blood & Wine DLCs are masterpieces",
      "Next-gen update brings ray tracing and visual improvements free",
      "Enormous world that rewards exploration",
    ],
    cons: [
      "Combat system is serviceable but not its strongest suit",
      "Inventory management is clunky",
    ],
    monetization: "Paid",
    performanceNotes:
      "Next-gen update is demanding at max settings. RT off yields stable 60 fps on mid-range GPUs.",
    monetizationNotes: "Base game + 2 expansions, all now bundled in Complete Edition.",
    steamUrl:
      "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
    reviewCount: 21500,
    userScore: 95,
  },
  {
    id: "g15",
    slug: "disco-elysium",
    title: "Disco Elysium",
    subtitle: "The Final Cut",
    coverImage: coverUrl("disco-elysium"),
    headerImage: coverUrl("disco-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("disco", i)),
    platforms: ["PC"],
    genres: ["RPG", "Detective"],
    tags: ["Story Rich", "Dialogue Heavy", "Philosophical", "Unique"],
    developer: "ZA/UM",
    publisher: "ZA/UM",
    releaseDate: "2019-10-15",
    description:
      "You're a detective with a unique skill system at your disposal and a whole city to explore. Interrogate unforgettable characters, crack murder cases or take bribes. Become a hero or an absolute disaster of a human being.",
    score: 93,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "The most literate game ever made. If you care about writing, philosophy, or detective fiction, this is essential.",
    pros: [
      "Unmatched writing quality in the RPG genre",
      "Skill system where your own psyche argues with you",
      "Deeply political without being preachy",
      "Full voice acting in The Final Cut (free update)",
    ],
    cons: [
      "No traditional combat — not for action seekers",
      "Can be slow-paced and text-heavy",
    ],
    monetization: "Paid",
    performanceNotes: "Runs well on modest hardware. Short loading times on SSD.",
    monetizationNotes: "One-time purchase. Final Cut content was a free upgrade.",
    steamUrl:
      "https://store.steampowered.com/app/632470/Disco_Elysium__The_Final_Cut/",
    reviewCount: 7800,
    userScore: 91,
  },
  {
    id: "g16",
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    subtitle: "Night City never sleeps",
    coverImage: coverUrl("cyberpunk"),
    headerImage: coverUrl("cyberpunk-header", 1200, 500),
    screenshots: [1, 2, 3, 4].map((i) => screenshotUrl("cyberpunk", i)),
    platforms: ["PC"],
    genres: ["Action RPG", "Open World"],
    tags: ["Cyberpunk", "FPS", "Story Rich", "Sci-Fi"],
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    releaseDate: "2020-12-10",
    description:
      "Night City is an open world driven by an intense narrative. Become V, a cyberpunk outlaw going after a one-of-a-kind implant that is the key to immortality. Customize your character, playstyle, and story in the most vibrant open city in games.",
    score: 76,
    verdictLabel: "WORTH IT",
    verdictSummary:
      "After years of patches and the Phantom Liberty DLC, Cyberpunk 2077 has become the game it promised to be. Worth it now.",
    pros: [
      "Night City is the most detailed open world ever built",
      "Phantom Liberty DLC is genuinely excellent",
      "Character builds are varied and fun after the 2.0 overhaul",
      "Brilliant main story and memorable characters (Judy, Panam, Johnny)",
    ],
    cons: [
      "Open-world activities outside quests lack depth",
      "Still has occasional bugs and AI quirks",
      "Needs high-end hardware for the best visual experience",
    ],
    monetization: "Paid",
    performanceNotes:
      "Path tracing requires RTX 40-series for smooth play. DLSS recommended. 30 fps minimum at 1080p on mid-range.",
    monetizationNotes: "Base game + one paid expansion (Phantom Liberty).",
    steamUrl:
      "https://store.steampowered.com/app/1091500/Cyberpunk_2077/",
    reviewCount: 16900,
    userScore: 74,
  },
  {
    id: "g17",
    slug: "vampire-survivors",
    title: "Vampire Survivors",
    subtitle: "Bullet heaven. Pure dopamine.",
    coverImage: coverUrl("vampire-survivors"),
    headerImage: coverUrl("vs-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("vs", i)),
    platforms: ["PC", "Android"],
    genres: ["Action", "Roguelike"],
    tags: ["Bullet Hell", "Casual", "Indie", "Addictive"],
    developer: "poncle",
    publisher: "poncle",
    releaseDate: "2022-10-20",
    description:
      "Mow down thousands of night creatures and let the gothic horror overwhelm you in this roguelike casual game. Vampire Survivors is a time-survival game with minimalist gameplay and maximalist payoff.",
    score: 87,
    verdictLabel: "WORTH IT",
    verdictSummary:
      "Absurdly addictive, astronomically cheap, and surprisingly deep. The king of the bullet-heaven genre.",
    pros: [
      "Incredibly satisfying power scaling every run",
      "Virtually endless content for the price",
      "Perfect for mobile gaming in short sessions",
      "Easy to learn, hard to master",
    ],
    cons: [
      "Visuals are intentionally rough — not for everyone",
      "Can feel repetitive after dozens of hours",
    ],
    monetization: "Paid",
    performanceNotes:
      "Runs on a toaster. 60 fps guaranteed on any modern device.",
    monetizationNotes:
      "One of the cheapest games ever made for the value. Paid DLCs at low prices.",
    steamUrl:
      "https://store.steampowered.com/app/1794680/Vampire_Survivors/",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.poncle.vampiresurvivors",
    reviewCount: 14100,
    userScore: 88,
    trending: true,
  },
  {
    id: "g18",
    slug: "diablo-immortal",
    title: "Diablo Immortal",
    subtitle: "Do you guys not have wallets?",
    coverImage: coverUrl("diablo-immortal"),
    headerImage: coverUrl("diablo-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("diablo", i)),
    platforms: ["PC", "Android"],
    genres: ["Action RPG", "MMORPG"],
    tags: ["Loot", "Multiplayer", "Controversial", "Grind"],
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    releaseDate: "2022-06-02",
    description:
      "Set between Diablo II and III, Diablo Immortal is a massively multiplayer action RPG that brings the Diablo franchise to mobile. The core gameplay loop is solid, but the monetization is among the most aggressive in gaming history.",
    score: 45,
    verdictLabel: "SKIP",
    verdictSummary:
      "Excellent core gameplay buried under one of the most predatory monetization systems ever designed. A cautionary tale.",
    pros: [
      "Combat mechanics are genuinely fun and Diablo-quality",
      "Visual and audio presentation is top-notch for mobile",
      "Story campaign is entertaining enough for a free playthrough",
    ],
    cons: [
      "Legendary gem upgrade system is grotesquely exploitative",
      "Estimated $100,000+ to fully gear a character",
      "PvP is completely pay-to-win",
      "Server-side throttling discourages free-to-play players",
    ],
    monetization: "Free with IAP",
    performanceNotes:
      "Runs well on midrange phones. PC version is technically a mobile port.",
    monetizationNotes:
      "Free to download. Monetization through legendary crests ($2.50 each), battle passes, and bundles. Widely criticized for predatory design.",
    steamUrl: "https://diabloimmortal.blizzard.com/",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.blizzard.diablo.immortal",
    reviewCount: 8900,
    userScore: 22,
  },
  {
    id: "g19",
    slug: "inscryption",
    title: "Inscryption",
    subtitle: "The cards are watching",
    coverImage: coverUrl("inscryption"),
    headerImage: coverUrl("inscryption-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("inscryption", i)),
    platforms: ["PC"],
    genres: ["Card Game", "Horror"],
    tags: ["Meta", "Puzzle", "Mystery", "Indie"],
    developer: "Daniel Mullins Games",
    publisher: "Devolver Digital",
    releaseDate: "2021-10-19",
    description:
      "Inscryption is an inky black card-based odyssey that blends the deckbuilding roguelike, escape-room style puzzles, and psychological horror into a blood-laced smoothie. Say nothing else. Just play it.",
    score: 91,
    verdictLabel: "MUST PLAY",
    verdictSummary:
      "A genre-defying experience that's best experienced knowing nothing. One of the most creative games of the decade.",
    pros: [
      "Constantly subverts expectations in ways you can't predict",
      "Card gameplay is genuinely excellent on its own merits",
      "Atmosphere is unforgettable",
      "Best experienced completely blind",
    ],
    cons: [
      "Some players may not enjoy the genre shifts",
      "Replay value is lower once you know the secrets",
    ],
    monetization: "Paid",
    performanceNotes: "Very lightweight. Runs on anything.",
    monetizationNotes: "One-time purchase. No additional content packs.",
    steamUrl: "https://store.steampowered.com/app/1092790/Inscryption/",
    reviewCount: 5600,
    userScore: 92,
  },
  {
    id: "g20",
    slug: "pubg-mobile",
    title: "PUBG Mobile",
    subtitle: "Winner winner chicken dinner",
    coverImage: coverUrl("pubg-mobile"),
    headerImage: coverUrl("pubg-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("pubg", i)),
    platforms: ["Android"],
    genres: ["Battle Royale", "Shooter"],
    tags: ["Multiplayer", "Competitive", "Tactical", "Squad"],
    developer: "Lightspeed & Quantum Studio",
    publisher: "Tencent Games",
    releaseDate: "2018-03-19",
    description:
      "The mobile battle royale that defined the genre on touchscreens. Drop, loot, and fight to be the last one standing across multiple maps. PUBG Mobile is a surprisingly authentic port of the PC experience.",
    score: 62,
    verdictLabel: "MIXED",
    verdictSummary:
      "Still the most tactical mobile battle royale, but years of bloat, bots, and aggressive monetization have dulled the edge.",
    pros: [
      "Core gunplay and tactical gameplay feel great on mobile",
      "Regular content updates with new maps and modes",
      "Large, active player base ensures short queue times",
    ],
    cons: [
      "Severe bot problem in lower ranks",
      "Aggressive in-app purchases and FOMO-driven events",
      "UI has become extremely cluttered over the years",
      "Heavy battery and storage demands",
    ],
    monetization: "Free with IAP",
    performanceNotes:
      "Needs a mid-range or better phone for smooth 60 fps. Graphics scaling options are generous.",
    monetizationNotes:
      "Free to play. Monetization through UC currency, Royale Pass, and cosmetic crates. Not pay-to-win for gameplay, but very aggressive cosmetics economy.",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.tencent.ig",
    reviewCount: 9200,
    userScore: 58,
  },
  {
    id: "g21",
    slug: "among-us",
    title: "Among Us",
    subtitle: "Trust no one",
    coverImage: coverUrl("among-us"),
    headerImage: coverUrl("among-us-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("among-us", i)),
    platforms: ["PC", "Android"],
    genres: ["Party", "Social Deduction"],
    tags: ["Multiplayer", "Casual", "Indie", "Deception"],
    developer: "Innersloth",
    publisher: "Innersloth",
    releaseDate: "2018-06-15",
    description:
      "Play online or over local WiFi with 4–15 players as you attempt to prep your spaceship for departure, but beware—one or more random players among the crew are Impostors bent on killing everyone.",
    score: 73,
    verdictLabel: "MIXED",
    verdictSummary:
      "A social phenomenon that's still fun with friends, but the magic has faded as a solo experience. Best in private lobbies.",
    pros: [
      "Incredible party game with the right group",
      "Cross-play between PC and mobile",
      "Free on Android",
      "New roles add strategic depth",
    ],
    cons: [
      "Public lobbies are often terrible",
      "Content updates are slow",
      "Core gameplay hasn't evolved much",
    ],
    monetization: "Free with IAP",
    performanceNotes: "Runs on everything. Minimal storage and RAM requirements.",
    monetizationNotes:
      "Free on mobile with ads and cosmetic IAP. Paid on PC with cosmetic IAP.",
    steamUrl: "https://store.steampowered.com/app/945360/Among_Us/",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.innersloth.spacemafia",
    reviewCount: 7300,
    userScore: 70,
  },
  {
    id: "g22",
    slug: "plague-inc",
    title: "Plague Inc.",
    subtitle: "Can you infect the world?",
    coverImage: coverUrl("plague-inc"),
    headerImage: coverUrl("plague-header", 1200, 500),
    screenshots: [1, 2, 3].map((i) => screenshotUrl("plague", i)),
    platforms: ["Android"],
    genres: ["Strategy", "Simulation"],
    tags: ["Dark Humor", "Educational", "Unique", "Single Player"],
    developer: "Ndemic Creations",
    publisher: "Ndemic Creations",
    releaseDate: "2012-05-26",
    description:
      "Plague Inc. is a unique mix of high strategy and terrifyingly realistic simulation. Your pathogen has just infected Patient Zero — now you must evolve to bring about the end of human history.",
    score: 79,
    verdictLabel: "WORTH IT",
    verdictSummary:
      "Darkly clever strategy that's more relevant than ever. Great for short sessions on mobile.",
    pros: [
      "Unique and addictive strategy concept",
      "Surprisingly educational about epidemiology",
      "Multiple pathogen types keep things fresh",
      "Frequent updates with pop-culture scenarios",
    ],
    cons: [
      "Later pathogens locked behind paywall",
      "Games can end in frustrating difficulty spikes",
    ],
    monetization: "Paid",
    performanceNotes: "Runs smoothly on all modern devices.",
    monetizationNotes:
      "Base game is paid. Additional pathogen types available as IAP.",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.miniclip.plagueinc",
    reviewCount: 4100,
    userScore: 78,
  },
];

/* ═══════════════════════════════════════════════════
   USERS
   ═══════════════════════════════════════════════════ */

export const users: User[] = [
  {
    id: "u1",
    username: "pixelpaladin",
    displayName: "Pixel Paladin",
    avatar: avatarUrl("pixelpaladin"),
    bio: "Indie games evangelist. If it has pixel art, I've probably played it.",
    gamesReviewed: 142,
    listsCreated: 8,
    joinedAt: "2024-03-15",
    favoriteGenres: ["Roguelike", "Metroidvania", "Indie"],
    recentActivity: [
      {
        id: "a1",
        type: "review",
        gameSlug: "hades-ii",
        gameTitle: "Hades II",
        rating: 95,
        createdAt: "2025-12-01",
      },
      {
        id: "a2",
        type: "rating",
        gameSlug: "dead-cells",
        gameTitle: "Dead Cells",
        rating: 88,
        createdAt: "2025-11-28",
      },
      {
        id: "a3",
        type: "list",
        listSlug: "best-roguelikes-2025",
        listTitle: "Best Roguelikes of 2025",
        createdAt: "2025-11-20",
      },
    ],
  },
  {
    id: "u2",
    username: "androidarchon",
    displayName: "Android Archon",
    avatar: avatarUrl("androidarchon"),
    bio: "Mobile gaming doesn't mean casual gaming. Proving it one review at a time.",
    gamesReviewed: 87,
    listsCreated: 5,
    joinedAt: "2024-06-10",
    favoriteGenres: ["Action RPG", "Strategy", "Puzzle"],
    recentActivity: [
      {
        id: "a4",
        type: "review",
        gameSlug: "genshin-impact",
        gameTitle: "Genshin Impact",
        rating: 76,
        createdAt: "2025-11-15",
      },
      {
        id: "a5",
        type: "review",
        gameSlug: "monument-valley",
        gameTitle: "Monument Valley",
        rating: 90,
        createdAt: "2025-11-10",
      },
    ],
  },
  {
    id: "u3",
    username: "criticalcrafter",
    displayName: "Critical Crafter",
    avatar: avatarUrl("criticalcrafter"),
    bio: "Writer, analyst, and occasional speed-runner. I believe every game deserves a fair review.",
    gamesReviewed: 203,
    listsCreated: 12,
    joinedAt: "2024-01-02",
    favoriteGenres: ["RPG", "Story Rich", "Open World"],
    recentActivity: [
      {
        id: "a6",
        type: "review",
        gameSlug: "baldurs-gate-3",
        gameTitle: "Baldur's Gate 3",
        rating: 98,
        createdAt: "2025-12-05",
      },
      {
        id: "a7",
        type: "list",
        listSlug: "rpgs-that-changed-gaming",
        listTitle: "RPGs That Changed Gaming Forever",
        createdAt: "2025-12-01",
      },
    ],
  },
  {
    id: "u4",
    username: "soulsborne_sam",
    displayName: "Soulsborne Sam",
    avatar: avatarUrl("soulsborne"),
    bio: "If it doesn't have a death screen, is it even a game?",
    gamesReviewed: 65,
    listsCreated: 3,
    joinedAt: "2024-08-22",
    favoriteGenres: ["Action RPG", "Soulslike", "Metroidvania"],
    recentActivity: [
      {
        id: "a8",
        type: "review",
        gameSlug: "elden-ring",
        gameTitle: "Elden Ring",
        rating: 97,
        createdAt: "2025-11-30",
      },
    ],
  },
];

/* ═══════════════════════════════════════════════════
   REVIEWS
   ═══════════════════════════════════════════════════ */

export const reviews: Review[] = [
  {
    id: "r1",
    gameId: "g1",
    gameSlug: "hades-ii",
    gameTitle: "Hades II",
    gameCover: coverUrl("hades-ii"),
    userId: "u1",
    username: "pixelpaladin",
    userAvatar: avatarUrl("pixelpaladin"),
    rating: 95,
    title: "Supergiant does it again — somehow even better",
    body: "I didn't think they could top the original, but Melinoë's story hits different. The new magic system adds layers of strategy Zagreus never had. The art direction in the surface world is breathtaking. After 80 hours, I'm still finding new interactions and dialogue. This is how you make a sequel.",
    pros: ["Incredible build variety", "Deeper narrative", "Stunning art"],
    cons: ["Some late-game balance issues"],
    helpful: 234,
    createdAt: "2025-12-01",
    platform: "PC",
  },
  {
    id: "r2",
    gameId: "g2",
    gameSlug: "elden-ring",
    gameTitle: "Elden Ring",
    gameCover: coverUrl("elden-ring"),
    userId: "u4",
    username: "soulsborne_sam",
    userAvatar: avatarUrl("soulsborne"),
    rating: 97,
    title: "The open world we've been waiting for since 2011",
    body: "FromSoftware finally gave their combat system the open world it deserved. Every cave, every ruin, every cliff edge hides something worth finding. Shadow of the Erdtree only made it better. I've put 400 hours in and I'm not done.",
    pros: ["Exploration is unmatched", "DLC is masterful", "Build diversity"],
    cons: ["Some bosses feel unfair solo"],
    helpful: 412,
    createdAt: "2025-11-30",
    platform: "PC",
  },
  {
    id: "r3",
    gameId: "g3",
    gameSlug: "baldurs-gate-3",
    gameTitle: "Baldur's Gate 3",
    gameCover: coverUrl("baldurs-gate-3"),
    userId: "u3",
    username: "criticalcrafter",
    userAvatar: avatarUrl("criticalcrafter"),
    rating: 98,
    title: "The RPG against which all others will be measured",
    body: "Larian pulled off something no one thought was possible: a D&D video game that actually feels like D&D. The sheer number of ways to solve problems is staggering. I've played through three times and each felt completely different. The multiplayer chaos is the best co-op experience I've ever had.",
    pros: ["Unrivaled reactivity", "Best in class writing", "4-player co-op"],
    cons: ["Act 3 performance issues"],
    helpful: 567,
    createdAt: "2025-12-05",
    platform: "PC",
  },
  {
    id: "r4",
    gameId: "g4",
    gameSlug: "stardew-valley",
    gameTitle: "Stardew Valley",
    gameCover: coverUrl("stardew-valley"),
    userId: "u2",
    username: "androidarchon",
    userAvatar: avatarUrl("androidarchon"),
    rating: 96,
    title: "The best $5 you'll ever spend on Android",
    body: "I play this on my commute and it's transformed my mornings. ConcernedApe's updates keep giving me reasons to start new farms. The touch controls work surprisingly well once you adjust. This is premium mobile gaming at its finest.",
    pros: ["Perfect mobile port", "Endless content", "Deeply relaxing"],
    cons: ["Auto-combat can be imprecise"],
    helpful: 189,
    createdAt: "2025-11-22",
    platform: "Android",
  },
  {
    id: "r5",
    gameId: "g7",
    gameSlug: "genshin-impact",
    gameTitle: "Genshin Impact",
    gameCover: coverUrl("genshin"),
    userId: "u2",
    username: "androidarchon",
    userAvatar: avatarUrl("androidarchon"),
    rating: 76,
    title: "Beautiful world, ugly business model",
    body: "Let me be clear: the exploration and combat in Genshin are genuinely excellent. Teyvat is one of the most beautiful game worlds on any platform. But the gacha is designed to create anxiety and FOMO in a way that borders on hostile. Play it free, enjoy the story, and resist the urge to spend.",
    pros: ["World design is incredible", "Combat is fluid", "Free story content"],
    cons: ["Predatory gacha", "Resin system", "Power creep"],
    helpful: 340,
    createdAt: "2025-11-15",
    platform: "Android",
  },
  {
    id: "r6",
    gameId: "g18",
    gameSlug: "diablo-immortal",
    gameTitle: "Diablo Immortal",
    gameCover: coverUrl("diablo-immortal"),
    userId: "u3",
    username: "criticalcrafter",
    userAvatar: avatarUrl("criticalcrafter"),
    rating: 30,
    title: "The most expensive free game ever made",
    body: "The gameplay is actually good — that's what makes this so frustrating. Blizzard built a quality ARPG and then wrapped it in the most predatory monetization system I've ever seen. Legendary gem upgrades are mathematically designed to encourage spending $100,000+. This is not a game — it's a casino wearing a game's skin.",
    pros: ["Core combat is great", "Production values are high"],
    cons: ["Grotesque monetization", "PvP is pay-to-win", "Insulting respect for player time"],
    helpful: 892,
    createdAt: "2025-10-20",
    platform: "PC",
  },
  {
    id: "r7",
    gameId: "g9",
    gameSlug: "hollow-knight",
    gameTitle: "Hollow Knight",
    gameCover: coverUrl("hollow-knight"),
    userId: "u1",
    username: "pixelpaladin",
    userAvatar: avatarUrl("pixelpaladin"),
    rating: 96,
    title: "Perfection for $15",
    body: "Hollow Knight is the game that made me care about Metroidvanias. The hand-drawn art is gorgeous, the bosses are brilliantly designed, and the world feels alive. The fact that Team Cherry gave away four massive content updates for free is almost unbelievable. I'll be playing this until Silksong arrives.",
    helpful: 445,
    createdAt: "2025-09-12",
    platform: "PC",
  },
  {
    id: "r8",
    gameId: "g17",
    gameSlug: "vampire-survivors",
    gameTitle: "Vampire Survivors",
    gameCover: coverUrl("vampire-survivors"),
    userId: "u1",
    username: "pixelpaladin",
    userAvatar: avatarUrl("pixelpaladin"),
    rating: 88,
    title: "3 dollars for 100 hours. Do the math.",
    body: "Vampire Survivors has no right being this addictive. You literally just move. That's it. But somehow the power fantasy of mowing down thousands of enemies with evolving weapons is the most satisfying thing I've played all year. The Android version is perfect for short sessions.",
    helpful: 267,
    createdAt: "2025-11-05",
    platform: "Android",
  },
  {
    id: "r9",
    gameId: "g12",
    gameSlug: "monument-valley",
    gameTitle: "Monument Valley",
    gameCover: coverUrl("monument"),
    userId: "u2",
    username: "androidarchon",
    userAvatar: avatarUrl("androidarchon"),
    rating: 90,
    title: "Interactive art that happens to be a game",
    body: "Monument Valley is less of a puzzle game and more of a meditative experience. Every screen could be framed and hung on a wall. It's short, but it's perfect. Sometimes less is more.",
    helpful: 156,
    createdAt: "2025-11-10",
    platform: "Android",
  },
  {
    id: "r10",
    gameId: "g5",
    gameSlug: "celeste",
    gameTitle: "Celeste",
    gameCover: coverUrl("celeste"),
    userId: "u4",
    username: "soulsborne_sam",
    userAvatar: avatarUrl("soulsborne"),
    rating: 93,
    title: "The closest a platformer has come to making me cry",
    body: "Celeste's gameplay is perfection — pixel-precise controls in hand-crafted levels that teach through play. But what elevates it is the story. Madeline's struggle with anxiety mirrors the gameplay loop of failing and trying again in a way that feels profound. The assist mode means everyone can experience this masterpiece.",
    helpful: 198,
    createdAt: "2025-10-01",
    platform: "PC",
  },
  {
    id: "r11",
    gameId: "g14",
    gameSlug: "the-witcher-3",
    gameTitle: "The Witcher 3: Wild Hunt",
    gameCover: coverUrl("witcher3"),
    userId: "u3",
    username: "criticalcrafter",
    userAvatar: avatarUrl("criticalcrafter"),
    rating: 97,
    title: "Still the RPG to beat after 10 years",
    body: "I replayed The Witcher 3 with the next-gen update and it still holds up better than 95% of modern RPGs. The Bloody Baron questline, Hearts of Stone's villain, Blood and Wine's fairy tale world — no other game has this consistency of narrative quality across 200+ hours of content.",
    helpful: 512,
    createdAt: "2025-08-15",
    platform: "PC",
  },
  {
    id: "r12",
    gameId: "g19",
    gameSlug: "inscryption",
    gameTitle: "Inscryption",
    gameCover: coverUrl("inscryption"),
    userId: "u1",
    username: "pixelpaladin",
    userAvatar: avatarUrl("pixelpaladin"),
    rating: 92,
    title: "Go in blind. Trust me.",
    body: "I can't say much without spoiling it. Just know that Inscryption is not the game you think it is. It's better. Much better. Buy it, play it, and don't look up guides. Thank me later.",
    helpful: 334,
    createdAt: "2025-07-20",
    platform: "PC",
  },
];

/* ═══════════════════════════════════════════════════
   CURATED LISTS
   ═══════════════════════════════════════════════════ */

export const lists: GameList[] = [
  {
    id: "l1",
    slug: "best-roguelikes-2025",
    title: "Best Roguelikes of 2025",
    description:
      "The roguelike genre is thriving. These are the titles that defined 2025 — each offering a unique twist on the die-and-retry formula.",
    coverImage: coverUrl("roguelikes-list", 800, 450),
    gameCount: 5,
    games: [games[0], games[5], games[10], games[16], games[18]],
    curatedBy: "pixelpaladin",
    createdAt: "2025-11-20",
    tags: ["Roguelike", "2025", "PC"],
  },
  {
    id: "l2",
    slug: "best-android-ports",
    title: "PC Games That Play Great on Android",
    description:
      "Not all mobile ports are created equal. These games made the jump from PC to Android without losing what made them special.",
    coverImage: coverUrl("android-ports-list", 800, 450),
    gameCount: 6,
    games: [games[3], games[5], games[6], games[9], games[10], games[16]],
    curatedBy: "androidarchon",
    createdAt: "2025-10-15",
    tags: ["Android", "Ports", "Mobile"],
  },
  {
    id: "l3",
    slug: "fair-monetization",
    title: "Fair Monetization on Mobile",
    description:
      "Mobile games that prove you don't need predatory IAP to make great software. Pay once, play forever — or free without the guilt.",
    coverImage: coverUrl("fair-money-list", 800, 450),
    gameCount: 5,
    games: [games[3], games[9], games[10], games[11], games[16]],
    curatedBy: "androidarchon",
    createdAt: "2025-09-01",
    tags: ["Fair", "Mobile", "Consumer-Friendly"],
  },
  {
    id: "l4",
    slug: "rpgs-that-changed-gaming",
    title: "RPGs That Changed Gaming Forever",
    description:
      "From The Witcher 3's open-world narratives to BG3's reactive storytelling — these RPGs pushed the genre forward and raised the bar for everyone.",
    coverImage: coverUrl("rpg-goats-list", 800, 450),
    gameCount: 5,
    games: [games[1], games[2], games[13], games[14], games[15]],
    curatedBy: "criticalcrafter",
    createdAt: "2025-12-01",
    tags: ["RPG", "Classics", "Story Rich"],
  },
  {
    id: "l5",
    slug: "indie-masterpieces",
    title: "Indie Games That Outshine AAA",
    description:
      "Small teams, massive impact. These indie titles deliver more heart, creativity, and polish than most blockbuster releases.",
    coverImage: coverUrl("indie-list", 800, 450),
    gameCount: 6,
    games: [games[0], games[4], games[5], games[8], games[10], games[18]],
    curatedBy: "pixelpaladin",
    createdAt: "2025-08-10",
    tags: ["Indie", "Must Play", "Hidden Gems"],
  },
  {
    id: "l6",
    slug: "games-to-skip",
    title: "Games That Disrespect Your Time (and Wallet)",
    description:
      "Some games look great but are designed to extract money rather than deliver fun. Here's our watchlist of titles to approach with extreme caution.",
    coverImage: coverUrl("skip-list", 800, 450),
    gameCount: 2,
    games: [games[17], games[19]],
    curatedBy: "criticalcrafter",
    createdAt: "2025-07-15",
    tags: ["Warning", "Predatory", "Monetization"],
  },
];

/* ═══════════════════════════════════════════════════
   ALL GENRES (for filter chips)
   ═══════════════════════════════════════════════════ */

export const allGenres: string[] = [
  "Action",
  "Action RPG",
  "Adventure",
  "Battle Royale",
  "Card Game",
  "Detective",
  "Endless Runner",
  "Horror",
  "Indie",
  "Metroidvania",
  "MMORPG",
  "Open World",
  "Party",
  "Platformer",
  "Puzzle",
  "Roguelike",
  "RPG",
  "Sandbox",
  "Shooter",
  "Simulation",
  "Social Deduction",
  "Strategy",
  "Survival",
  "Turn-Based Strategy",
];

export const allYears: string[] = [
  "2025",
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",
  "2014",
  "2012",
  "2011",
];
